### ISSUE TITLE
Komiser with global region access is a blocker with AWS SCP policy restriction with limited region access.

### ISSUE THREAD

**Issue by halodoc2021** [HelloOraculi/komiser#223]
**Describe the bug**
Komiser with global region access is a blocker with AWS SCP policy restriction with limited region access.

**To Reproduce**
1. In helm chart when we set the region as ap-southeast-1, komiser is unable to describecluster or any other resource and share the data in dashboard.
2. All resource usage is not visible in Komiser dashboard, lots of notification with error code 500.

**Expected behavior**
Komiser should support customer to handle region specific cost visualisation dashboard. Currently it is set open to all region, whereas AWS SCP restriction will not let the account to enable access to all regions.

**Screenshots**
If applicable, add screenshots or Loom video to help explain your problem.

![image](https://user-images.githubusercontent.com/86966515/190153829-b8d0f153-05ce-404e-b463-d9a116b74cd6.png)

**Additional context**

Images and/or videos showing the bug:

- The link where the bug happened.
- The cloud provider you were interacting with.
- The email of the account you were using.
- The browser/device you were using.

**Comment by jakepage91** [comment]
Thanks a million for writing out the issue @halodoc2021, as mentioned on Discord, we will do our best to bump the priority of this feature and will reach out to you as progress is made.

If other community members would like to bump the priority of the feature request, feel free to do so on the [public roadmap](https://oraculi.canny.io/). You can find the feature request in the `planned` column.  

All the best from the Oraculi team.

**Comment by jakepage91** [comment]
Hey there @halodoc2021, I'm happy to say that we have been able to deliver this feature. Thanks to @mlabouardy for the speedy turnaround! 

I will shortly update the Komiser documentation but for now feel free to try out the feature by: 

- Installing Komiser version `2.11.0` 
- Pass in the `--regions` flag separated by commas. 
Ex. `komiser start --regions  eu-central-1,us-east-1,us-west-2` 

Passing in the `--regions flag` will designate the regions that data will be retrieved from, making it easier to be more granular and directed about the regions we access with Komiser. Please let us know if you have any issues and if you have any feedback. 

All the best from the Oraculi team.

**Comment by halodoc2021** [comment]
Thanks @mlabouardy for the quick fix and releasing the version. I have tested this in our environment. Most of the error notification reported earlier got fixed. There are couple of notification, will investigate and revert. Once again thanks a ton @jakepage91 & @mlabouardy

**Comment by mlabouardy** [comment]
Thanks a lot for requesting the feature @halodoc2021  :)
